flu: Business.cpp City.cpp Flu_Manager.cpp Household.cpp Location.cpp Multi_City_Main.cpp Person.cpp SimulationRun.cpp
	# g++ -mcmodel=large -g -gdwarf-2 -std=c++11 -fopenmp Business.cpp City.cpp Flu_Manager.cpp Household.cpp Location.cpp Multi_City_Main.cpp Person.cpp SimulationRun.cpp -o FluSimulation -lm
	# g++ -mcmodel=large -O3 -std=c++11 -fopenmp -ltbb Business.cpp City.cpp Flu_Manager.cpp Household.cpp Location.cpp Multi_City_Main.cpp Person.cpp SimulationRun.cpp -o FluSimulation_1109 -lm
	 g++ -mcmodel=large -O3 -std=c++11 -fopenmp Business.cpp City.cpp Flu_Manager.cpp Household.cpp Location.cpp Multi_City_Main.cpp Person.cpp SimulationRun.cpp -o FluSimulation_1221 -lm
